title: SotE Dev Blog
author: iesous-kurios
email: j.wylie.81@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  For me to live is Christ; to die is gain.  This is a place to record my daily dieing to self while I try to learn how to develop software.

# social links
twitter_username: iesouskurios # DO NOT include the @ character, or else the build will fail!
github_username:  iesous-kurios # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
